version: '3'

services:
  scraping:
    build: 
      context: ./scraping
    command: ./node_modules/.bin/ts-node src/index.ts
    environment:
      - SCREENSHOT_PATH=/app/picture
      - DIST_FILEPATH=/app/dist/beatmania.txt
    volumes: 
      - './scraping:/app/'
    working_dir: /app
  scraping-init:
    image: node:10.15.3-alpine
    command: yarn
    volumes: 
      - './scraping:/app/'
    working_dir: /app
  preprocessing:
    image: jupyter/datascience-notebook
    command: python index.py
    volumes: 
      - './preprocessing:/app/'
    working_dir: /app
